[reticulum]
  enable_transport = False
  share_instance = Yes
  instance_name = qortal-masque-relay

[logging]
  loglevel = 4

[interfaces]
  [[Local Qortal Hub]]
    type = BackboneInterface
    enabled = Yes
    remote = 127.0.0.1
    target_port = 4243
    network_name = qortal-hub
    passphrase = qortal-hub-community-mesh-v1

  [[Qortal Backbone Primary]]
    type = BackboneInterface
    enabled = Yes
    remote = phantom.mobilefabrik.com
    target_port = 4400
    network_name = qortal-hub

  [[Qortal Backbone]]
    type = BackboneInterface
    enabled = Yes
    remote = reticulum.qortal.link
    target_port = 4444
    network_name = qortal-hub

  [[Qortal Backbone 2]]
    type = BackboneInterface
    enabled = Yes
    remote = reticulum2.qortal.link
    target_port = 4444
    network_name = qortal-hub

  [[Qortal Backbone 3]]
    type = BackboneInterface
    enabled = Yes
    remote = reticulum3.qortal.link
    target_port = 4444
    network_name = qortal-hub

  [[Qortal Backbone 4]]
    type = BackboneInterface
    enabled = Yes
    remote = reticulum4.qortal.link
    target_port = 4444
    network_name = qortal-hub

  [[Qortal Backbone 5]]
    type = BackboneInterface
    enabled = Yes
    remote = reticulum5.qortal.link
    target_port = 4444
    network_name = qortal-hub
